# version: "3.8"

# services:
#   # 데이터베이스
#   postgres:
#     image: postgres:15
#     container_name: postgres_db
#     restart: always
#     environment:
#       POSTGRES_DB: healthcare
#       POSTGRES_PASSWORD: test123
#       POSTGRES_USER: test123
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data

#   # 라디오 SNS
#   radio:
#     build:
#       context: ./radio_sns
#     container_name: radio_sns
#     restart: always
#     depends_on:
#       - postgres
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./app:/app
#     command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

# volumes:
#   pgdata:

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: healthcare
      POSTGRES_USER: test123
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test123 -d healthcare"]
      interval: 5s
      timeout: 3s
      retries: 20

  radio:
    build:
      context: ./radio_sns
      dockerfile: Dockerfile
    container_name: radio_sns
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pgdata:
